### ISSUE TITLE
ChromoDynamics V2

### ISSUE THREAD

**Issue by yousefabuz17** [MagicStack/Chromodynamics#13]
This isn't really an issue. Just wanted to say I changed the colors on this theme so its more brighter and vibrant colors. I modified it and it turned out extremely great. I was wondering if you can check it out I will leave a couple of screenshots and even the link for it as i published it on vscode but not taking credit for anything. I truly enjoy the making of this theme youse created. All I honestly did was change most of the hex colors to my own preference nothing more. Hope you like it. 
https://marketplace.visualstudio.com/items?itemName=yousefabuz17.ChromodynamicsV2&ssr=false#overview

<img width="1552" alt="Screen Shot 2020-08-13 at 10 42 39 PM" src="https://user-images.githubusercontent.com/68834704/90208266-754d2d80-ddb6-11ea-9e57-5fc2d36e3e3f.png">
<img width="1552" alt="Screen Shot 2020-08-13 at 10 43 25 PM" src="https://user-images.githubusercontent.com/68834704/90208268-75e5c400-ddb6-11ea-85ea-14d4130526f9.png">
<img width="1552" alt="Screen Shot 2020-08-13 at 10 59 35 PM" src="https://user-images.githubusercontent.com/68834704/90209190-ae869d00-ddb8-11ea-8eb0-c6b76ce5343d.png">

**Comment by 1st1** [comment]
This looks great! I'm glad we inspired you to create a spinoff!
