### ISSUE TITLE
White tabs in Atom

### ISSUE THREAD

**Issue by nikolay** [MagicStack/Chromodynamics#2]
Most of the general syntax highlighting is broken and worst of all - all tabs turn white.

**Comment by 1st1** [comment]
Hm, I don't see that.  Could you please attach a screenshot?  What kind of files are affected?

**Comment by 1st1** [comment]
Should be fixed in v0.0.6

**Comment by nikolay** [comment]
Thanks, @1st1! The white tab got fixed, but many files don't get syntax highlighting yet - like Nginx, for example.

**Comment by nikolay** [comment]
@1st1 Sorry, my bad. I just had the syntax disabled. Duh!

**Comment by 1st1** [comment]
NP!
