### ISSUE TITLE
fyi:  not avail in atom

### ISSUE THREAD

**Issue by Dowwie** [MagicStack/Chromodynamics#7]
I couldn't find Chromodynamics within Themes of Atom 1.14.2

**Comment by tennyson-mccalla** [comment]
@Dowwie I'm using 1.14.3 and found it but I doubt it's much different. At first I couldn't find it but I was on the "packages" tab instead of the "themes" tab.

Here's the atom.io link if it helps:
https://atom.io/themes/Chromodynamics

**Comment by 1st1** [comment]
> I'm using 1.14.3 and found it but I doubt it's much different. At first I couldn't find it but I was on the "packages" tab instead of the "themes" tab.

Yeah, @Dowwie can you make sure you search within "Themes"?
